/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-var-requires */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
"use server";
const stripe = require("stripe")(process.env.STRIPE_PRIVATE_KEY);

/**
 * Creates a new Stripe customer account for a user.
 *
 * @param firstName - The first name of the user.
 * @param lastName - The last name of the user.
 * @param email - The email address of the user.
 * @returns A Promise that resolves to the customer ID generated by Stripe.
 */
const createUserStripeAccount = async (
  firstName: string,
  lastName: string,
  email: string,
): Promise<string> => {
  // Instantiate the stripe api

  const customer = await stripe.customers.create({
    name: `${firstName} ${lastName}`,
    email: email,
  });
  const customerId: string = customer.id;

  return customerId;
  // return the customer id to be added to the user account in mongo
};

export default createUserStripeAccount;
